export const FETCH_BASE_CURRENCY_DATA = "FETCH_BASE_CURRENCY_DATA";
export const UPDATE_BASE = "UPDATE_BASE";
export const UPDATE_TO_CURRENCY = "UPDATE_TO_CURRENCY";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const UPDATE_CURRENCY_BALANCES = "UPDATE_CURRENCY_BALANCES";
export const UPDATE_CURRENCIES_ARRAY = "UPDATE_CURRENCIES_ARRAY";
